### ISSUE TITLE
enable to get it

### ISSUE THREAD

**Issue by ghost** [redcode-labs/Coldfire#35]
1) go get github.com/redcode-labs/Coldfire: invalid github.com import path "github.com/redcode-labs"

2) mports github.com/redcode-labs/Coldfire
	imports github.com/redcode-labs/Coldfire: import cycle not allowed

any help please ??

**Comment by ManicDevs** [comment]
As far as I am noticing on the current stable release of go, and fetching the git there are no issues.

root@devel:~/go/src/cerberus# go version
go version go1.18.1 linux/amd64


root@devel:~/go/src/cerberus# go get github.com/redcode-labs/Coldfire
go: downloading github.com/redcode-labs/Coldfire v0.0.0-20211214081201-051297330fcc

- Could you possible give any further help, - Is this a clean build, have you previously fetched this git, or otherwise. Is your go binary up to-date?

**Comment by ManicDevs** [comment]
root@devel:~/go/src/cerberus# go version
go version go1.18.1 linux/amd64

**Comment by ManicDevs** [comment]
Could you possibly give any further details, 
 - Is this the most up to date go binary setup and or - Have you previously attempted or successfully fetched the git.
 
 As far as I notice I am able to currently pull the latest git using the latest stable go binary.
 
---------

root@devel:~/go/src/example# go version
go version go1.18.1 linux/amd64

root@devel:~/go/src/example# go get github.com/redcode-labs/Coldfire
go: downloading github.com/redcode-labs/Coldfire v0.0.0-20211214081201-051297330fcc
